# Utiliser l'image officielle de MySQL comme base
FROM mysql:5.7

USER root
RUN yum update -y && yum install -y curl
USER mysql

# Copier le fichier init.sql dans le répertoire /docker-entrypoint-initdb.d
RUN curl -o /docker-entrypoint-laravel.d/laravel.sql https://raw.githubusercontent.com/redhox/laravel_blog_2/master/laravel.sql
# Exposer le port 3306
EXPOSE 3306

