# Utiliser l'image officielle de MySQL comme base
FROM mysql:5.7

USER root
RUN yum update -y && yum install -y wget


# Copier le fichier init.sql dans le répertoire /docker-entrypoint-initdb.d
RUN wget https://raw.githubusercontent.com/redhox/laravel_blog_2/master/laravel.sql
COPY laravel.sql /docker-entrypoint-initdb.d/
USER mysql
# Exposer le port 3306
#EXPOSE 3306

